/*
 * Automatically generated file. DO NOT EDIT.
 * Espressif IoT Development Framework (ESP-IDF)  Configuration Header
 */
#pragma once
#define CONFIG_RV_WATER_PUMP_RELAY 15
#define CONFIG_RV_PRESS_CONTROL_RELAY 14
#define CONFIG_WP_RUST_PROTECTION_RUN_TIME 2
#define CONFIG_WP_PC_CLEAR_FAILURE_TIME 5
#define CONFIG_WAPU_DEBUG 1
#define CONFIG_USART_STDIN 1
#define CONFIG_USART_STDOUT 1
#define CONFIG_USART_STDERR 2
#define CONFIG_RV_DEBUG 1
#define CONFIG_UOUT_HAVE_COMPONENT 1
#define CONFIG_UOUT_PUBLISH_LOG_AS_TXT 1
#define CONFIG_UOUT_PUBLISH_IP_ADDR_AS_TXT 1
#define CONFIG_REQUIRE_ROOT_OBJECT 1
#define CONFIG_UOUT_DEBUG 1
#define CONFIG_TXTIO_HAVE_COMPONENT 1
#define CONFIG_APP_UART_BAUD_RATE 115200
#define CONFIG_APP_USE_CLI_TASK 1
#define CONFIG_CLI_DEBUG 1
